# Generated by Django 2.0.2 on 2018-04-30 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_author_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
